### ISSUE TITLE
delete mover and files with special characters...

### ISSUE THREAD

**Issue by scottblomquist** [sdsc/lustre-data-mover#3]
Hi,

I bumped into an issue with the delete mover.  Files with strange characters error out.  I had two files that I have the logs for one with a control-M and another named @&t@.

Here is the log with the file with a control M
<pre>
2017-04-15 11:52:26,271 - ERROR [cmover_del.py:185 -            checkFile()] - Error removing file /.../mcdexp-svnh/Icon
Traceback (most recent call last):
  File "/home/root/lustre-data-mover/lustre-data-mover/cmover_del.py", line 180, in checkFile
    os.remove(dst)
OSError: [Errno 2] No such file or directory: '/.../mcdexp-svnh/Icon'
</pre>

The one with named @&t@ the process seemed to recurse adding '/' to the path...

<pre>
OSError: [Errno 2] No such file or directory: '/.../automake1.13/t/instspc.dir////////a'
2017-04-17 01:43:28,745 - ERROR [cmover_del.py:121 -               delDir()] - Error removing dir /.../automake-1.13/t/instspc.dir//////////a
Traceback (most recent call last):
  File "/home/root/lustre-data-mover/lustre-data-mover/cmover_del.py", line 118, in delDir
    shutil.rmtree(dir)
  File "/home/root/lustre-data-mover/miniconda2/lib/python2.7/shutil.py", line 239, in rmtree
    onerror(os.listdir, path, sys.exc_info())
  File "/home/root/lustre-data-mover/miniconda2/lib/python2.7/shutil.py", line 237, in rmtree
    names = os.listdir(path)

OSError: [Errno 2] No such file or directory: '/.../automake-1.13/t/instspc.dir//////////a'
2017-04-17 01:49:09,781 - ERROR [cmover_del.py:121 -               delDir()] - Error removing dir /.../automake-1.13/t/instspc.dir///////////a
Traceback (most recent call last):
  File "/home/root/lustre-data-mover/lustre-data-mover/cmover_del.py", line 118, in delDir
    shutil.rmtree(dir)
  File "/home/root/lustre-data-mover/miniconda2/lib/python2.7/shutil.py", line 239, in rmtree
    onerror(os.listdir, path, sys.exc_info())
  File "/home/root/lustre-data-mover/miniconda2/lib/python2.7/shutil.py", line 237, in rmtree
    names = os.listdir(path)

OSError: [Errno 2] No such file or directory: '/.../automake-1.13/t/instspc.dir///////////a'
2017-04-17 01:58:30,811 - ERROR [cmover_del.py:121 -               delDir()] - Error removing dir /.../automake-1.13/t/instspc.dir////////////a
....
</pre>

Thanks again for everything.

**Comment by dimm0** [comment]
There's a new go version of the data mover. This one is not being actively developed anymore
